Repository FM-Five-men/Fashion-Manager, pull requests merged in 2025-09, with the labels that each got.

#4 Kimseungmin select category feature
  .github/PULL_REQUEST_TEMPLATE.md
  fashion-manager/src/main/java/fashionmanager/kim/develop/MessageCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/ReportCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/ReviewCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/config/CategoryConfiguration.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/controller/CategoryController.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/MessageCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/ReportCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/ReviewCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/service/CategoryService.java
  fashion-manager/src/main/resources/application.yml
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/MessageCategoryMapper.xml
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/ReportCategoryMapper.xml
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/ReviewCategoryMapper.xml
  fashion-manager/src/test/java/fashionmanager/kim/develop/CategoryServiceTest.java
Labels: Feature

#9 후기, 신고, 쪽지 카테고리 요소 추가, 수정, 삭제 기능 개발
  fashion-manager/build.gradle
  fashion-manager/src/main/java/fashionmanager/kim/develop/controller/CategoryController.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/MessageCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/ReportCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/ReviewCategoryDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/MessageCategory.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/ReportCategory.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/ReviewCategory.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/MessageCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/ReportCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/ReviewCategoryMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/repository/MessageCategoryRepository.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/repository/ReportCategoryRepository.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/repository/ReviewCategoryRepository.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/service/CategoryService.java
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/MessageCategoryMapper.xml
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/ReportCategoryMapper.xml
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/ReviewCategoryMapper.xml
  fashion-manager/src/test/java/fashionmanager/kim/develop/CategoryServiceTest.java
Labels: Feature

#12 해시태그 조회, 추가, 수정, 삭제 기능 개발
  fashion-manager/src/main/java/fashionmanager/kim/develop/controller/CategoryController.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/controller/HashTagController.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/FashionHashTagDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/FashionPostDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/HashTagAndPostDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/dto/HashTagDTO.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/FashionHashTag.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/FashionHashTagPK.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/FashionPost.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/HashTag.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/mapper/HashTagMapper.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/repository/HashTagRepository.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/service/HashTagService.java
  fashion-manager/src/main/resources/fashionmanager/kim/develop/mapper/HashTagMapper.xml
  fashion-manager/src/test/java/fashionmanager/kim/develop/HashTagServiceTest.java
Labels: Feature

#18 [Features] #15 게시판 작성/수정/삭제 기능 구현
  fashion-manager/build.gradle
  fashion-manager/src/main/java/fashionmanager/baek/develop/aggregate/PostType.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/config/AppConfig.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/PostController.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/PostServiceFactory.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/ModifyDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/RequestRegistPostDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/ResponseRegistPostDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/entity/FashionPost.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/repository/FashionPostRepository.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/FashionPostServiceImpl.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/PostService.java
Labels: Feature, Refactoring

#25 comment 기능 추가
  .idea/material_theme_project_new.xml
  .idea/misc.xml
  .idea/workspace.xml
  fashion-manager/build.gradle
  fashion-manager/src/main/java/fashionmanager/FashionManagerApplication.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/entity/FashionPost.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/config/AppConfiguration1.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/controller/CommentController.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/dto/CommentDTO.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/dto/CommentPostDTO.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/entity/Comment.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/mapper/CommentMapper.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/repository/CommentRepository.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/service/CommentService.java
  fashion-manager/src/main/resources/fashionmanager/lee/develop/mapper/CommentMapper.xml
  fashion-manager/src/test/java/fashionmanager/kim/develop/CategoryServiceTest.java
Labels: Feature

#32 댓글에 대한 좋아요&힘내요 구현
  fashion-manager/src/main/java/fashionmanager/lee/develop/controller/CommentController.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/dto/CommentReactionDTO.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/entity/CommentReaction.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/entity/CommentReactionId.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/repository/CommentReactionRepository.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/service/CommentService.java
  fashion-manager/src/main/resources/fashionmanager/lee/develop/mapper/CommentMapper.xml
  fashion-manager/src/test/java/fashionmanager/lee/develop/service/CommentServiceTest.java
Labels: Feature

#60 주석 제거
  fashion-manager/src/main/java/fashionmanager/lee/develop/controller/CommentController.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/entity/Comment.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/service/CommentService.java
Labels: Bug

#65 오류 수정
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/PostController.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/PostService.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/controller/CommentController.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/dto/CommentDTO.java
  fashion-manager/src/main/java/fashionmanager/lee/develop/dto/CommentPostDTO.java
Labels: Bug

#75 [Features] 게시물 좋아요/힘내요 기능 구현, 페이지네이션 구현
  fashion-manager/src/main/java/fashionmanager/baek/develop/config/BaekWebConfig.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/FashionPostController.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/MentoringPostController.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/controller/ReviewPostController.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/Criteria.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/PageDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/PhotoDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/ReactionRequestDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/dto/ReactionResponseDTO.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/entity/PostReactionEntity.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/mapper/FashionPostMapper.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/mapper/MentoringPostMapper.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/mapper/ReviewPostMapper.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/repository/PostReactionRepository.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/FashionPostService.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/MentoringPostService.java
  fashion-manager/src/main/java/fashionmanager/baek/develop/service/ReviewPostService.java
  fashion-manager/src/main/resources/fashionmanager/baek/develop/mapper/FashionPostMapper.xml
  fashion-manager/src/main/resources/fashionmanager/baek/develop/mapper/MentoringPostMapper.xml
  fashion-manager/src/main/resources/fashionmanager/baek/develop/mapper/ReviewPostMapper.xml
  fashion-manager2/src/main/java/fashionmanager/baek/develop/config/BaekWebConfig.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/controller/FashionPostController.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/controller/MentoringPostController.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/controller/ReviewPostController.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/dto/Criteria.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/dto/PageDTO.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/dto/PhotoDTO.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/dto/ReactionRequestDTO.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/dto/ReactionResponseDTO.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/entity/PostReactionEntity.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/mapper/FashionPostMapper.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/mapper/MentoringPostMapper.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/mapper/ReviewPostMapper.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/repository/PostReactionRepository.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/service/FashionPostService.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/service/MentoringPostService.java
  fashion-manager2/src/main/java/fashionmanager/baek/develop/service/ReviewPostService.java
  fashion-manager2/src/main/resources/fashionmanager/baek/develop/mapper/FashionPostMapper.xml
  fashion-manager2/src/main/resources/fashionmanager/baek/develop/mapper/MentoringPostMapper.xml
  fashion-manager2/src/main/resources/fashionmanager/baek/develop/mapper/ReviewPostMapper.xml
Labels: Feature

#77 리드미 수정
  README.md
  image/요구사항1.png
  image/요구사항2.png
Labels: Feature

#83 Features 를 main으로 merge
  .idea/workspace.xml
  eureka-gateway/.gradle/8.14.3/executionHistory/executionHistory.bin
  eureka-gateway/.gradle/8.14.3/executionHistory/executionHistory.lock
  eureka-gateway/.gradle/8.14.3/fileHashes/fileHashes.bin
  eureka-gateway/.gradle/8.14.3/fileHashes/fileHashes.lock
  eureka-gateway/.gradle/8.14.3/fileHashes/resourceHashesCache.bin
  eureka-gateway/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  eureka-gateway/.gradle/buildOutputCleanup/cache.properties
  eureka-gateway/.gradle/buildOutputCleanup/outputFiles.bin
  eureka-gateway/.gradle/file-system.probe
  eureka-gateway/.idea/gradle.xml
  eureka-gateway/.idea/modules/eurekagateway.main.iml
  eureka-gateway/.idea/workspace.xml
  eureka-server/.gradle/8.14.3/checksums/checksums.lock
  eureka-server/.gradle/8.14.3/executionHistory/executionHistory.bin
  eureka-server/.gradle/8.14.3/executionHistory/executionHistory.lock
  eureka-server/.gradle/8.14.3/fileHashes/fileHashes.bin
  eureka-server/.gradle/8.14.3/fileHashes/fileHashes.lock
  eureka-server/.gradle/8.14.3/fileHashes/resourceHashesCache.bin
  eureka-server/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  eureka-server/.gradle/buildOutputCleanup/cache.properties
  eureka-server/.gradle/buildOutputCleanup/outputFiles.bin
  eureka-server/.gradle/file-system.probe
  eureka-server/.idea/gradle.xml
  eureka-server/.idea/workspace.xml
  fashion-manager/src/main/java/fashionmanager/kim/develop/security/JwtAuthenticationFilter.java
  fashion-manager/src/main/java/fashionmanager/kim/develop/security/SecurityConfiguration.java
  fashion-manager2/.gradle/8.14.3/checksums/checksums.lock
  fashion-manager2/.gradle/8.14.3/checksums/md5-checksums.bin
  fashion-manager2/.gradle/8.14.3/checksums/sha1-checksums.bin
  fashion-manager2/.gradle/8.14.3/executionHistory/executionHistory.bin
  fashion-manager2/.gradle/8.14.3/executionHistory/executionHistory.lock
  fashion-manager2/.gradle/8.14.3/fileHashes/fileHashes.bin
  fashion-manager2/.gradle/8.14.3/fileHashes/fileHashes.lock
  fashion-manager2/.gradle/8.14.3/fileHashes/resourceHashesCache.bin
  fashion-manager2/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  fashion-manager2/.gradle/buildOutputCleanup/outputFiles.bin
  fashion-manager2/.gradle/file-system.probe
  fashion-manager2/.idea/modules/fashion_manager.main.iml
  fashion-manager2/.idea/workspace.xml
  fashion-manager2/build.gradle
  fashion-manager2/build/reports/problems/problems-report.html
  fashion-manager2/build/tmp/compileJava/previous-compilation-data.bin
  fashion-manager2/src/main/java/fashionmanager/kim/develop/config/SwaggerConfiguration.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/controller/MemberController.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/dto/MemberRightDTO.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/security/JwtAuthenticationFilter.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/security/JwtTokenProvider.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/security/SecurityConfiguration.java
  fashion-manager2/src/main/java/fashionmanager/kim/develop/service/MemberService.java
Labels: Feature, Refactoring
